### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by adamgiesinger** [JMPerez/spotify-web-api-js#102]
Hey,
I've been working with this API a bit and I really like it. I have one question. As far as I know, normally you get an authorization code and a refresh code (at least it is like that in my Java application, where it generates the new codes automatically). Here I have to generate a new access code often by myself because else the "access token is invalid" (401).
Am I doing something wrong or is refreshing the codes not possible with JavaScript?
Thank you,
Adam

**Comment by JMPerez** [comment]
This wrapper is intended to be used client-side. You set the access token obtained through the implicit grant flow or the authorization code one. The latter needs to happen server-side, so you can provide your client secret in a secure way.

If you need to refresh your token you need to make a request server-side, then pass the access token to the browser. A way you can implement this is that the browser makes a request to your backend to refresh the token when it gets a 401 response from the Web API.

Let me know if that helps.

**Comment by adamgiesinger** [comment]
Thank you! Resolved my issue. :)
