### ISSUE TITLE
September Playlist API Updates

### ISSUE THREAD

**Issue by jmfortunatojr** [JMPerez/spotify-web-api-js#103]
Reference: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

Will this library be updated to be in compliance to with the new endpoints?

**Comment by JMPerez** [comment]
@jmfortunatojr The intention is to keep the library up to date with changes in the Web API. Unfortunately I don't have much time these days to contribute and it might take longer than expected. The project is open sourced and PRs are more than welcome in case anyone wants to give a helping hand.

**Comment by jmfortunatojr** [comment]
Thanks. I just fixed the node version, and will put in a pull request for this version as well.

**Comment by gate5th** [comment]
Hey guys - it looks like Spotify delayed implementation of the changes to the Playlist API indefinitely (https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/). I am getting 400 errors for creating playlists now. I can do a workaround in my app, but wanted to let you know.
