### ISSUE TITLE
remove userId from Create playlist method

### ISSUE THREAD

**Issue by amelialaundy** [JMPerez/spotify-web-api-js#110]
Me again, the changes just released to update the playlist endpoints as per the new Spotify URIs (https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/)
https://github.com/JMPerez/spotify-web-api-js/pull/105https://github.com/JMPerez/spotify-web-api-js/releases/tag/v1.1.0  don't include an update for Creating a playlist without the userId:

`POST /v1/me/playlists`

I'll create a PR for this URI too, to remove the userId from the request.

**Comment by JMPerez** [comment]
Fixed
