### ISSUE TITLE
latest release will have broken typescript integrations

### ISSUE THREAD

**Issue by amelialaundy** [JMPerez/spotify-web-api-js#111]
Release 1.1.0 didnt update the typescript bindings so the code doesn't require userId anymore but the bindings don't reflect that meaning that anyone writing typescript will still be calling the functions with the userId and it won't create the URI correctly
![screen shot 2018-08-24 at 8 30 55 am](https://user-images.githubusercontent.com/7699279/44550704-1fba8900-a779-11e8-992a-f49bf034fc45.png)

I can do a PR too

**Comment by JMPerez** [comment]
Fixed and published!
