### ISSUE TITLE
An example

### ISSUE THREAD

**Issue by dennisfrijlink** [JMPerez/spotify-web-api-js#117]
At the moment I'm building a Sonos web-controller and I'm looking for a method to use the Spotify API via HTML/JS. After hours of searching I found your web-api, but I can't figure out how to use it via javascript. Is it possible you give me an example of an web-app running with this api (including the HTML, JS files)?

**Comment by JMPerez** [comment]
You can have a look [at this project](https://github.com/RohaanAdvani68/spotifyPlayer). Also, all the projects listed on https://github.com/JMPerez/spotify-web-api-js/network/dependents have this library as a dependency.

It should be a good start.

If you feel like you need something easier, you can find [a tutorial on Spotify's developer site that explains how to set up an application step by step](https://developer.spotify.com/documentation/web-api/quick-start/).
