### ISSUE TITLE
Add optional parameter 'market' to getTrack and getTracks

### ISSUE THREAD

**Issue by lynnpark** [JMPerez/spotify-web-api-js#129]
getTrack and getTracks have an optional parameter 'market'. This is needed in order to get a non-null value for the preview_url field.

**Comment by lynnpark** [comment]
I can't tell if this is still maintained. Are PRs being accepted?

**Comment by JMPerez** [comment]
@lynnpark Unfortunately I have very little time these days to get involved in this project. There is an open issue asking for new maintainers on https://github.com/JMPerez/spotify-web-api-js/issues/114

**Comment by JMPerez** [comment]
Closing the issue. `market` can be passed in the `options` parameter got both `getTrack()` and `getTracks()`.
