### ISSUE TITLE
createPlaylist 401 error

### ISSUE THREAD

**Issue by mlam28** [JMPerez/spotify-web-api-js#138]
Hi,

When trying to create a playlist for a user, i keep getting a 401 error, 'no token provided', even though I have already set the access token using .setAccessToken.

I do not know what is wrong could you please assist? Here is my code;
<img width="497" alt="Screen Shot 2019-09-30 at 12 59 12 AM" src="https://user-images.githubusercontent.com/48364991/65850653-b9118280-e31d-11e9-8407-e8dc06f66c28.png">

**Comment by kevinguebert** [comment]
Ah, this was close. I just tested it locally and ran into the same problems with your code.
I was able to make it work by removing the `JSON.stringify` call. My request now looks like this:
`spotifyApi.createPlaylist(spotifyId, {name: "New Playlist"}).then(resp => console.log(resp));`

Let me know if that doesn't work for you!

**Comment by JMPerez** [comment]
Closing this issue. The `createPlaylist` function expects a JSON object as `options`, so removing `JSON.stringify()` should make it work. Thanks @kevinguebert for supporting.
