### ISSUE TITLE
search optional JSON object error 'limit'

### ISSUE THREAD

**Issue by mlam28** [JMPerez/spotify-web-api-js#139]
When trying to increase the limit of results received from the api, passing in an addition JSON object of {limit: 50} does not work, it still defaults to 20.

my code:
let options = JSON.stringify({limit: 50})
        spotifyApi.setAccessToken(token)
        spotifyApi.searchTracks(input, options)

Is there a way around this or am I missing something?

Thanks,
Michelle

**Comment by kevinguebert** [comment]
Looks like this may also be similar to #138 - there is not a need to `JSON.stringify`. It should just be `spotifyApi.searchTracks(input, {limit: 50})`

**Comment by JMPerez** [comment]
Closing this issue. The `searchTracks` function expects a JSON object as `options`, so removing `JSON.stringify()` should make it work. Thanks @kevinguebert for supporting.
