### ISSUE TITLE
Trouble with getting playlist/adding track to playlist

### ISSUE THREAD

**Issue by erin2722** [JMPerez/spotify-web-api-js#147]
I am trying to create a react web app that edits user playlists but keep running into a 404: invalid playlist ID error when using any of the functions that access playlists. Everything else (including getting a list of user playlists) is working fine. I also tested the playlist ID on Spotify's website and so I know that it is valid. I attached screenshots of my code and the error message. Thank you so much for your help!
<img width="895" alt="Screen Shot 2020-01-06 at 6 31 01 PM" src="https://user-images.githubusercontent.com/16248113/71856812-308c4600-30b3-11ea-920d-439946bdb6ef.png">
<img width="541" alt="Screen Shot 2020-01-06 at 6 31 19 PM" src="https://user-images.githubusercontent.com/16248113/71856823-384bea80-30b3-11ea-9248-ec72b9dc89b5.png">

**Comment by kevinguebert** [comment]
@erin2722 so it looks like there is an issue somewhere with the API endpoint that is being called. In the `POST` request it is sending it to `api.spotify.com/v1/users/{playlist_id}/playlists/{[tracks]}`...when it should instead be going to `POST https://api.spotify.com/v1/playlists/{playlist_id}/tracks`.  But, looking at the definition of [`addTracksToPlaylist`](https://github.com/JMPerez/spotify-web-api-js/blob/1f6fa3948e0c996b2a44b4429e0bf2dbe92d11c4/src/spotify-web-api.js#L785) it doesn't seem to be adding in the `users/{playlist_id}` part. I ran a quick test application locally and it worked for me.

This may then take some debugging - are you altering `spotifyWebAPI` at all anywhere? Also, do you have the correct scopes to edit a playlist? They should be `playlist-modify-public` and `playlist-modify-private`.

**Comment by erin2722** [comment]
Thank you for your reply! Adding a blank string as the first argument in my function call fixed it `spotifyWebAPI.addTracksToPlaylist('', '4u3BK21IWkEpcd8ydK7liu', songs)`
