### ISSUE TITLE
Breaking TypeScript default export change undocumented

### ISSUE THREAD

**Issue by Jabokoe** [JMPerez/spotify-web-api-js#149]
The 1.1.0 to 1.1.1 update was actually a breaking change for TypeScript users. (For JS consumers it could make sense for it to be a minor or patch.) The change to using default export typings is a welcome one but of course breaks existing import statements.

The usage for TypeScript for use with Webpack could be updated in README
```ts
import SpotifyWebApi from 'spotify-web-api-js';

let spotify = new SpotifyWebApi();
```
While this may be obvious to seasoned TS users working with default exports to not use `{}` or `* as` [here is an explanation for others still learning](https://www.typescriptlang.org/docs/handbook/modules.html#default-exports). This works through the 1.1.1 to the current 1.2.0 releases.

This simplified import should resolve errors like TS2694 `Namespace ... /spotify-web-api-js/src-typings/spotify-web-api has no exported member SpotifyWebApiJs`, TS2305 `Module ... /spotify-web-api-js/src/typings/spotify-web-api has no exported member SpotifyWebApi` and error TS2351.

**Comment by JMPerez** [comment]
Fixed changing the README on https://github.com/JMPerez/spotify-web-api-js/commit/1487329717fc12665bd9b983b71040609bdb4069. Should have caught this one and ship a major update due to the breaking change.

The amendment in README will prevent other users from hitting this issue.
