### ISSUE TITLE
QUESTION: Where to handle expired tokens

### ISSUE THREAD

**Issue by suryapolina99** [JMPerez/spotify-web-api-js#174]
Where do we handle expired access tokens so we can replace it with the refresh token or redirect user to login page. Expired token errors point to line 123 
           `req.send(null);`
and I want to redirect user to login page here but it ends up going to login page every-time if I redirect it after this line

**Comment by JMPerez** [comment]
@suryapolina99 When the user's access token expires, the following requests will fail. When they do you get the request in the callback function, and can check its `status` property. If it's 401, then the user is not authorized to access that resource or make that request.

Assuming the user did have access before, getting a 401 means their token expired.
