### ISSUE TITLE
How do i get my access token?

### ISSUE THREAD

**Issue by ColdtQ** [JMPerez/spotify-web-api-js#182]

**Comment by JMPerez** [comment]
In order to get an access token you need to create an app and implement one of the authentication flows supported by Spotify's API. I would recommend you to check out https://developer.spotify.com/documentation/general/guides/authorization-guide/.

**Comment by ianwalter** [comment]
Sorry to comment on a closed issue, but why isn't the token endpoint implemented as part of the library? It's part of the same API right? Would you accept a PR for this? Thanks!
