### ISSUE TITLE
Browserify cannot find module 'spotify-web-api-js'

### ISSUE THREAD

**Issue by joakimbugge** [JMPerez/spotify-web-api-js#21]
Is Browserify actually supported? I get the following error on bundle:

```
Error: Cannot find module 'spotify-web-api-js' from '/Users/Joakim/web/nattliv/resources/assets/js/app/music'
```

Seems like Browserify can't find the spotify-web-api-js module in `node_modules`. When I manually add the `main` attribute in `package.json` to tell it where the script resides, I get the this error:

`Uncaught TypeError: object is not a function`

when doing:

```
var Spotify = require('spotify-web-api-js');
var api = new Spotify();

console.log(api);
```

**Comment by JMPerez** [comment]
Thanks for the report, @joakimbugge. I'm going to check what's going on.

**Comment by joakimbugge** [comment]
That was fast! :) I just wanted to add that the error contains `/Users/Joakim/web/nattliv/resources/assets/js/app/music` because that's the `basedir` in my Browserify and it tries to find the module there when it can't find it in `node_modules`.

**Comment by JMPerez** [comment]
It seems that the published version on npm is version 0.13.0, which is missing, amongst others, [this commit](https://github.com/JMPerez/spotify-web-api-js/commit/7ef3df2f2a5382712cf4ec9d6ff87200ab7e1289).

I have just published the current version (0.15.0) and it seems to work with browserify. Could you reinstall the dependency and try it out again?

**Comment by joakimbugge** [comment]
Works like a dream now! :)

**Comment by JMPerez** [comment]
Great! I will try not to forget to publish the version next time :) Thanks for spotting it!
