### ISSUE TITLE
Get a user's songs from Your Music

### ISSUE THREAD

**Issue by scotty914** [JMPerez/spotify-web-api-js#22]
Is it possible to get a user's songs from Your Music? In the desktop app, that is normally on the left in the middle under Your Music.

**Comment by JMPerez** [comment]
@scotty914 Yes! You can use [`getMySavedTracks()`](http://jmperezperez.com/spotify-web-api-js/#getMySavedTracks) for fetching the tracks that the user has saved in their "Your Music" section.

**Comment by scotty914** [comment]
Awesome. Thank you!
