### ISSUE TITLE
getUserPlaylists doesn't return the correct number of playlists every time

### ISSUE THREAD

**Issue by scotty914** [JMPerez/spotify-web-api-js#29]
The call getUserPlaylists, which I've modified a tiny bit, doesn't return the correct number of playlists everytime. I have 11 playlists and sometimes it returns all 11 and sometimes it returns just 6 of them.

Constr.prototype.getUserPlaylists = function(userId, options, callback) {
    var requestData = {
      url: _baseUri + '/users/' + userId + '/playlists' + '?offset=' + options.offset + '&limit=50'
    };
    return _checkParamsAndPerformRequest(requestData, options, callback);
  };

![screen shot 2016-01-24 at 9 57 23 am](https://cloud.githubusercontent.com/assets/5743500/12537924/ec26716a-c280-11e5-8c1d-9ef5265f52ef.png)

I should note that I haven't updated this file with the Github repo is a very long time (about 1 year ago) and this error started occurring for me about 4-5 months ago and has been happening pretty consistently.

When it doesn't load them all

![screen shot 2016-01-24 at 10 00 04 am](https://cloud.githubusercontent.com/assets/5743500/12537954/91301120-c281-11e5-8e43-009792ca48e5.png)

![screen shot 2016-01-24 at 10 00 53 am](https://cloud.githubusercontent.com/assets/5743500/12537957/9f49c972-c281-11e5-847a-3632788936f2.png)

When it does load them all
![screen shot 2016-01-24 at 10 06 13 am](https://cloud.githubusercontent.com/assets/5743500/12537995/30466854-c282-11e5-9a57-4508dfe1ab3b.png)
![screen shot 2016-01-24 at 10 06 29 am](https://cloud.githubusercontent.com/assets/5743500/12537996/352ef5d4-c282-11e5-85c1-cd9ccb7b3ef3.png)
![screen shot 2016-01-24 at 10 06 37 am](https://cloud.githubusercontent.com/assets/5743500/12537997/38183d00-c282-11e5-8a88-a79c70651046.png)

**Comment by JMPerez** [comment]
@scotty914 I see that you are using a different access token in each call. I don't know whether both access tokens have the same scopes granted.

If the request is always the same (same URL, headers and body), then there is not a problem in the wrapper, and we should file a ticket in the Spotify's Web API GitHub repo instead. But before doing that, make sure that the exactly the same request is getting different responses.

**Comment by scotty914** [comment]
Hi. Sorry for the late reply.

As far as I can tell, they are the same exact calls. Only difference I can see is the Etag (which I'd expect to change) and the Auth Bearer token change. The only scope I ever give users is ['user-read-private', 'playlist-read', 'playlist-read-private', 'playlist-read-collaborative'] so I can't see that being the issue. The url is always the same, the request body is always the same (except for Bearer token) and response headers are always the same except for the Etag.

**Comment by JMPerez** [comment]
Then this does look like an issue in the Web API. I would recommend you to file an issue in the [Web API repo](https://github.com/spotify/web-api/issues). I have gone through the open issues and can't see a similar one there. They might be able to help you.

Since the wrapper seems to be handling the request and response correctly, I'm going to close this ticket for now. Feel free to reopen it if you find more info.
