### ISSUE TITLE
Release on npm not up to date

### ISSUE THREAD

**Issue by andialbrecht** [JMPerez/spotify-web-api-js#30]
Thanks for a great library. However, running "npm install" installs version 0.15.0, but not the most recent release. Are there any issues that prevent uploading newer releases to npmjs?

**Comment by JMPerez** [comment]
@andialbrecht I have just published to npm the latest version. I forgot to run the command in the latest releases.

Thanks for noticing!

**Comment by andialbrecht** [comment]
Great, thanks!

José Manuel Pérez <notifications@github.com> schrieb am So., 28. Feb. 2016
07:51:
