### ISSUE TITLE
Search suggestion

### ISSUE THREAD

**Issue by ewal** [JMPerez/spotify-web-api-js#31]
Hi, just a suggestion: wouldn't be enough to have a single search method and just pass the types in the options object? In my app I search for `tracks, albums` and `artists` and it just looks kinda strange in the code that I use `searchTracks` when the result back contains all three types.

regards, Emil

**Comment by JMPerez** [comment]
@ewal That's a great suggestion. I will add a generic search function that can receive a list of types.
