### ISSUE TITLE
Promise.defer is not part of the Promises/A+ spec

### ISSUE THREAD

**Issue by kirbysayshi** [JMPerez/spotify-web-api-js#36]
`.defer` is tested to determine if the promise implementation is valid within this utility, but `.defer` is an extension provided by some libraries, like Q. Therefore the error message is extremely misleading.

for example, using the native Promise provided by ES2015 would fail in Firefox and Safari:

```
spotifyApi.setPromiseImplementation(Promise);
// Throws saying not A+ compatible
```

`.defer` appears to be still in chrome, but is not defined in Safari or Firefox. It is deprecated and not on a standards track: https://bugzilla.mozilla.org/show_bug.cgi?id=1034599

**Comment by JMPerez** [comment]
@kirbysayshi You are right. I think I was trying to find something in common amongst several Promise polyfills when I started the project. I will fix this to either remove or fix the check.

**Comment by kirbysayshi** [comment]
Cool! Looks good.
