### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by EyesBear** [JMPerez/spotify-web-api-js#49]
I ran into this error when trying to use the api, and I had to insert "var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;" inside spotify-web-api.js for it to work.

**Comment by JMPerez** [comment]
@EyesBear This library is intended to be used in the browser, where `XMLHttpRequest` should be defined. If you want to use the library on Node.JS I would recommend you to have a look at https://github.com/thelinmichael/spotify-web-api-node, which has a similar API.

**Comment by smooJitter** [comment]
So this wouldn't work with react-native

**Comment by JMPerez** [comment]
To be honest, I'm not sure about it sincr so haven't tried it yet. According to https://facebook.github.io/react-native/docs/network.html react-native does implement `XMLHttpRequest` so it should work out of the box.
