### ISSUE TITLE
Album instead of track

### ISSUE THREAD

**Issue by calixto111** [JMPerez/spotify-web-api-js#53]
hi , JMPerez,
this is the website I refered to
http://michaeldick.me/YetAnotherSpotifyPlaylistConverter/
how can I edit this to get a different result , I mean album uri , instead of track?
thanks

**Comment by JMPerez** [comment]
Please, ask the author of the site for this. You can use its GitHub repo for that https://github.com/bertique/YetAnotherSpotifyPlaylistConverter .
