### ISSUE TITLE
Is there a way to send URI through the body instead of URI ?

### ISSUE THREAD

**Issue by cassioscabral** [JMPerez/spotify-web-api-js#54]
Hi there, I'm using this wrapper and it's being great. I'm having a problem when trying to use the `addTracksToPlaylist` with 100 URI, the limit set by Spotify. I got a 414 error, request URI too long. I can see that `replaceTracksInPlaylist` uses `postData: {uris: uris}` instead of `params: {uris: uris }` like `addTracksToPlaylist`. So I was wondering if `addTracksToPlaylist` couldn't use the body as welll instead of params. 

`replaceTracksInPlaylist` it's working fine.

My case is that I'm reordering my playlist using `replaceTracksInPlaylist` to replace the first 100 and iterate over chunks of 100 more tracks to add into the playlist. But eventually got this error.

Maybe I can help making a PR for that, just asking before doing anything.

Thanks

**Comment by JMPerez** [comment]
@cassioscabral Have you tried with the latest version of the library ([0.21.2](https://github.com/JMPerez/spotify-web-api-js/releases/tag/v0.21.2)). It includes a fix for this issue.

**Comment by cassioscabral** [comment]
@JMPerez no, I didn't, my bad. Thanks for replying
