### ISSUE TITLE
Is there any support for OAuth?

### ISSUE THREAD

**Issue by simonghales** [JMPerez/spotify-web-api-js#55]
Hey there, thanks for putting this together. I was wondering if there was any support provided for OAuth? I had a look through the source code and documentation, and it appears there isn't. Maybe I'm missing something?

Cheers,

Simon

**Comment by JMPerez** [comment]
The library only wraps the calls to api.spotify.com. Depending on what authorization flow you want to use you might find [this node.js wrapper](https://github.com/thelinmichael/spotify-web-api-node/) useful (especially if implementing the authorization code flow), or if you plan to use client credentials you can check how https://github.com/JMPerez/spotify-iquiz or https://github.com/JMPerez/spotify-dedup

**Comment by simonghales** [comment]
Thanks for the quick response, I'll have a look at those links.
