### ISSUE TITLE
Missing "Get Current User’s Recently Played Tracks" endpoint

### ISSUE THREAD

**Issue by JMPerez** [JMPerez/spotify-web-api-js#57]
The wrapper is missing the [Get Current User’s Recently Played Tracks](https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/) See [the blog post announcing it](https://developer.spotify.com/news-stories/2017/03/01/new-endpoint-recently-played-tracks/).

**Comment by skovmand** [comment]
And the Typescript typings for it.

**Comment by JMPerez** [comment]
@skovmand is there any way to import the fixtures in the `spotify-api-tests.ts` file? It would reduce duplication and make the file more maintainable.

**Comment by skovmand** [comment]
Hi José

Thanks for your work!

Unfortunately I'm very busy right now and don't have the resources to look
on it. So it will have to wait for a while. Sorry!
