### ISSUE TITLE
Instructions for Ionic 2/3 typescript app

### ISSUE THREAD

**Issue by shawns582** [JMPerez/spotify-web-api-js#64]
Im a newbie to typescript and am trying to add this to my Ionic 2 app. Can someone give me step by step instructions on how to add this? I tried:

npm install -S spotify-web-api-js
then browserify spotify-web-api.js -o spotifybundle.js  (on the file in the node_modules folder)
then add spotifybundle.js to my index.html
I also tried doing a typings install with all the *.d.ts files provided and still cant get it working (I get "SpotifyWebApi is not defined" when I try to make the call var spotify = new SpotifyWebApi() ).  

thanks in advance.  

P.S. I am using this instead of the angular-spotify version bc it seems more frequently updated.

**Comment by JMPerez** [comment]
@shawns582 Have you checked that you are making the request to the bundle file from the browser correctly and that you are importing the `SpotifyWebApi` variable? The library exports it but you need to import it from your code, or make it available in the global scope for you to access it.

**Comment by adizam** [comment]
Yo @shawns582... I know its been like, 8 months.. but did you ever resolve your issue?

**Comment by JMPerez** [comment]
Closing the issue for now. Feel free to reopen it if needed.
