### ISSUE TITLE
Change /next from PUT to POST

### ISSUE THREAD

**Issue by jpmsegurado** [JMPerez/spotify-web-api-js#69]
Whenever I try to change execute the `/next` method, it gives me the 405 not allowed method. I found out it was because the method of the request was `PUT` and not `POST`. This little change was the solution locally for me :)

**Comment by JMPerez** [comment]
That's weird, according to [the docs](https://developer.spotify.com/web-api/skip-users-playback-to-next-track) and [the console](https://developer.spotify.com/web-api/console/post-next/) it should be `POST`.

I have just tried it and it seems to work with `POST`. Could you double check?

**Comment by jpmsegurado** [comment]
In your code it is post, I don't know why in my node_modules it was put...

**Comment by JMPerez** [comment]
You are right, the published package still uses PUT since it doesn't contain this fix https://github.com/JMPerez/spotify-web-api-js/commit/4f3c2967ba6ffe90aded9149a24f719c8b12f200. I'm going to publish the new version.

**Comment by JMPerez** [comment]
Published with version 0.22.1!
