### ISSUE TITLE
Promise abort not working

### ISSUE THREAD

**Issue by tmm42** [JMPerez/spotify-web-api-js#80]
Trying to implement the search functionalities with the promise implementation i run into some trouble.

My implementation is as written in the documentation. I've initialized the promises with the Q library `spotifyApi.setPromiseImplementation(Q);` . Following the example from the documentation:

```javascript
var prev = null;

function onUserInput(queryTerm) {

  // abort previous request, if any
  if (prev !== null) {
    prev.abort();
  }

  // store the current promise in case we need to abort it
  prev = spotifyApi.search(queryTerm, ['album', 'artist', 'playlist', 'track'], {'limit': 20, 'offset': 0})
    .then(function(data) {

      // clean the promise so it doesn't call abort
      prev = null;

      // ...render list of search results...

    }, function(err) {
      console.error(err);
    });
}
```

Running this, i receive the error that the abort function doesn't exist. `prev.abort is not a function`.

As I see while debugging the script, the abort function is wrapped in the return value, but accessing the object which is stored in `prev` isn‘t possible besäuselt the abort function isn't represented anymore.

Is there anything I'm missing out?

**Comment by JMPerez** [comment]
@tmm42 you are right, the `abort` function doesn't work properly. It turns out that the function is added to the promise returned by `search()`, but not to the one returned when chaining `then()`.

A workaround would be to do like this:

```js
var prev = null;

function onUserInput(queryTerm) {

  // abort previous request, if any
  if (prev !== null) {
    prev.abort();
  }

  // store the current promise in case we need to abort it
  prev = spotifyApi.search(queryTerm, ['album', 'artist', 'playlist', 'track'], {'limit': 20, 'offset': 0});
  prev.then(function(data) {

      // clean the promise so it doesn't call abort
      prev = null;

      // ...render list of search results...

    }, function(err) {
      console.error(err);
    });
}
```

**Comment by tmm42** [comment]
This workaround is fixing the problem. Thank you very much @JMPerez !

**Comment by JMPerez** [comment]
Great! I have updated the README fixing the example.
