### ISSUE TITLE
[Typescript] Types for the Player endpoint are not defined

### ISSUE THREAD

**Issue by sandervspl** [JMPerez/spotify-web-api-js#88]
functions like `Constr.getMyCurrentPlayingTrack` do not have their types defined. Will these be added some time soon?

**Comment by JMPerez** [comment]
@sandervspl I don't have much experience with Typescript typings. @skovmand has made a great job adding typings to the library, but there might be some recent methods that were added without updating the typings.

Any help is appreciated so if you know how to add them you are more than welcome to do so.

**Comment by JMPerez** [comment]
Fixed
