### ISSUE TITLE
[Question] Struggling getting play and pausing working

### ISSUE THREAD

**Issue by Yarael-Poof** [JMPerez/spotify-web-api-js#97]
Hi
I'm having trouble getting .play() and .pause() working. I'm using an icon as a button to playwhatever track is current paused on the users current device. I am doing this using React. I have managed to get this api working fine so far until this. Here is the code for my button (it works fine for calling other functions)
`<span onClick={() => spotifyApi.play()}> <i class="material-icons" style={{fontSize: 48}}>play_arrow</i> </span>`

When I then click on the button I get the following error:

> TypeError: right-hand side of 'in' should be an object, got undefined

After looking at the documentation of this library and the spotify api docs it seems that the device Id is optional and that if I call .play() it will just unpuase the music on whatever the active device is? 
I tried passing the device object to .play() from getMyCurrentPlaybackState and this didn't give me an error but didn't actually unpause the music.

Any help would be appreciated.

**Comment by JMPerez** [comment]
@Yarael-Poof This is a bug in the library, that shouldn't require `options` to be defined.
A work-around for now is to pass `{}` as the first parameter:

```js
<span onClick={() => spotifyApi.play({})}> <i class="material-icons" style={{fontSize: 48}}>play_arrow</i> </span>
```
