### ISSUE TITLE
removeFromMySavedAlbums returns 400 missing payload

### ISSUE THREAD

**Issue by wdehoog** [JMPerez/spotify-web-api-js#98]
Calling removeFromMySavedAlbums returned '400 missing payload'. 

Changing
```
    postData: albumIds 
```
into
```
    params: {
         ids: albumIds.join(',')
    }
```
made it work

**Comment by wdehoog** [comment]
removeFromMySavedTracks() suffers from the same problem

**Comment by JMPerez** [comment]
Hi @wdehoog! Could you provide a code snippet with the code you are trying to run? It does work on my end here.

```js
const a = new SpotifyWebApi();
a.setAccessToken('...');
a.removeFromMySavedAlbums(['1FMBWnJQwTFcS4xc4Ma5VK', '4HneBDs6M2hyeqtmLCCTXR']);
```

**Comment by wdehoog** [comment]
Really? Then I'll close the issue. I use your lib on my sailfish phone. It's javascript engine might be the cause. It is rather old. 
Sorry for this and many thanks for the library.

**Comment by JMPerez** [comment]
@wdehoog It should work just fine there. The library uses very basic Javacript to increase compatibility (so no fancy async/await, fetch, etc). If you find out any additional details, please reopen the issue.

**Comment by wdehoog** [comment]
@JMPerez it seems the Qt version on SailfishOS does not support a http DELETE request with a body. The body (the payload) is not sent.

**Comment by JMPerez** [comment]
Interesting... I know that some APIs support a `method` parameter so you can send a POST command that actually deletes (eg `method=DELETE`), but Spotify's web api doesn't support it afaik.

**Comment by JMPerez** [comment]
I prefer using the method to send data in the body since it doesn't have the stricter length limit that the query parameter version has. It's also better in general so the information from the URL doesn't end up in server logs.
